"""Export data contracts, JSON schemas, TypeScript types, and registries.

Usage:
    uv run python -m animated_infographics.contracts.export [--out DIR]
"""

import argparse
import json
import subprocess
from pathlib import Path
from typing import Any

from animated_infographics.contracts.icons import ICON_NAMES
from animated_infographics.contracts.models import (
    Beats,
    Bible,
    Storyboard,
    Timeline,
    Transcript,
    VoiceDecision,
)
from animated_infographics.contracts.styles import StyleSpec
from animated_infographics.contracts.templates import REGISTRY

HEADER_COMMENT = "GENERATED by animated_infographics.contracts.export — DO NOT EDIT"


def generate_schema(model: type[Any]) -> dict[str, Any]:
    """Generate deterministic JSON schema with standard header comment."""
    schema = model.model_json_schema()
    schema["$comment"] = HEADER_COMMENT
    return schema


def generate_icon_map_ts(icon_names: tuple[str, ...]) -> str:
    """Generate TypeScript icon map using explicit named imports."""
    sorted_names = sorted(icon_names)
    import_lines = [f"  {name}Icon," for name in sorted_names]
    map_lines = [f"  {name}: {name}Icon," for name in sorted_names]

    lines = [
        f"/* {HEADER_COMMENT} */",
        "",
        "import {",
        *import_lines,
        "  type Icon,",
        '} from "@phosphor-icons/react";',
        "",
        "export const ICON_MAP: Record<string, Icon> = {",
        *map_lines,
        "};",
        "",
    ]
    return "\n".join(lines)


def generate_template_registry_json() -> dict[str, Any]:
    """Generate template registry dictionary with header comment."""
    registry_dict: dict[str, Any] = {
        "$comment": HEADER_COMMENT,
    }
    for name in sorted(REGISTRY.keys()):
        registry_dict[name] = REGISTRY[name].model_dump(mode="json")
    return registry_dict


def generate_contracts_ts(timeline_schema: dict[str, Any], project_root: Path) -> str:
    """Invoke json-schema-to-typescript via npx to produce TypeScript definitions."""
    renderer_dir = project_root / "renderer"
    schema_str = json.dumps(timeline_schema, indent=2, sort_keys=True)

    result = subprocess.run(
        ["npx", "--prefix", str(renderer_dir), "json2ts", "--unknownAny"],
        input=schema_str,
        text=True,
        capture_output=True,
        check=True,
    )
    ts_code = result.stdout
    # json2ts adds /* eslint-disable */ which triggers an unused-directive warning in eslint
    if ts_code.startswith("/* eslint-disable */\n"):
        ts_code = ts_code[len("/* eslint-disable */\n") :]
    return f"/* {HEADER_COMMENT} */\n\n{ts_code}"


def export_all(out_dir: Path, project_root: Path) -> None:
    """Export all contract files into target directory."""
    schema_dir = out_dir / "schema"
    renderer_gen_dir = out_dir / "renderer" / "src" / "generated"

    schema_dir.mkdir(parents=True, exist_ok=True)
    renderer_gen_dir.mkdir(parents=True, exist_ok=True)

    # 1. Schemas
    schemas = {
        "voice.schema.json": generate_schema(VoiceDecision),
        "transcript.schema.json": generate_schema(Transcript),
        "bible.schema.json": generate_schema(Bible),
        "beats.schema.json": generate_schema(Beats),
        "storyboard.schema.json": generate_schema(Storyboard),
        "timeline.schema.json": generate_schema(Timeline),
        "styles.schema.json": generate_schema(StyleSpec),
    }

    for filename, schema in schemas.items():
        filepath = schema_dir / filename
        filepath.write_text(json.dumps(schema, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    # 2. Template Registry
    reg_path = renderer_gen_dir / "templateRegistry.json"
    reg_data = generate_template_registry_json()
    reg_path.write_text(json.dumps(reg_data, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    # 3. Icon Names
    icon_names_path = renderer_gen_dir / "iconNames.json"
    icon_names_path.write_text(json.dumps(sorted(ICON_NAMES), indent=2) + "\n", encoding="utf-8")

    # 4. Icon Map TS
    icon_map_path = renderer_gen_dir / "iconMap.ts"
    icon_map_path.write_text(generate_icon_map_ts(ICON_NAMES), encoding="utf-8")

    # 5. Contracts TS
    contracts_path = renderer_gen_dir / "contracts.ts"
    contracts_ts = generate_contracts_ts(schemas["timeline.schema.json"], project_root)
    contracts_path.write_text(contracts_ts, encoding="utf-8")

    # 6. Styles TS
    styles_path = renderer_gen_dir / "styles.ts"
    styles_ts = generate_contracts_ts(schemas["styles.schema.json"], project_root)
    styles_path.write_text(styles_ts, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Export schemas and types")
    parser.add_argument("--out", type=Path, default=None, help="Output directory")
    args = parser.parse_args()

    # Locate repository root relative to this file
    project_root = Path(__file__).resolve().parent.parent.parent.parent
    out_dir = args.out.resolve() if args.out else project_root

    export_all(out_dir, project_root)
    print(f"Exported schemas and types to {out_dir}")


if __name__ == "__main__":
    main()
