import * as fs from "node:fs";
import * as path from "node:path";

const projectRoot = path.resolve(__dirname, "../..");
const vendorLakesPath = path.join(projectRoot, "data/vendor/ne_50m_lakes.geojson");
const outPath = process.argv[2]
  ? path.resolve(process.argv[2])
  : path.join(projectRoot, "renderer/public/geo/lakes-50m.json");

if (!fs.existsSync(vendorLakesPath)) {
  console.error(`ne_50m_lakes.geojson not found at ${vendorLakesPath}`);
  process.exit(1);
}

const raw = JSON.parse(fs.readFileSync(vendorLakesPath, "utf-8"));

function roundCoord(c: unknown): unknown {
  if (typeof c === "number") {
    return Math.round(c * 1000) / 1000;
  }
  if (Array.isArray(c)) {
    return c.map(roundCoord);
  }
  return c;
}

const result = {
  $comment: "GENERATED by renderer/scripts/gen-lakes.ts — DO NOT EDIT",
  type: "FeatureCollection",
  features: raw.features.map((f: { type: string; properties?: { name?: string }; geometry: { type: string; coordinates: unknown } }) => ({
    type: "Feature",
    properties: {
      name: f.properties?.name || "",
    },
    geometry: {
      type: f.geometry.type,
      coordinates: roundCoord(f.geometry.coordinates),
    },
  })),
};

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, JSON.stringify(result, null, 2) + "\n", "utf-8");
console.log(`Wrote ${result.features.length} lakes to ${outPath}`);
