import * as fs from "node:fs";
import * as path from "node:path";
import * as d3 from "d3-geo";
import * as topojson from "topojson-client";
import type { Topology } from "topojson-specification";

interface CountryProperties {
  name?: string;
}

interface CountryFeature extends GeoJSON.Feature<GeoJSON.Geometry, CountryProperties> {
  id?: string | number;
}

const projectRoot = path.resolve(__dirname, "../..");
const countryInfoPath = path.join(projectRoot, "data/vendor/countryInfo.txt");
const outPath = process.argv[2]
  ? path.resolve(process.argv[2])
  : path.join(projectRoot, "data/geo/country_bboxes.json");
const countryCodesOutPath = process.argv[3]
  ? path.resolve(process.argv[3])
  : path.join(projectRoot, "renderer/src/generated/countryCodes.ts");

if (!fs.existsSync(countryInfoPath)) {
  console.error(`countryInfo.txt not found at ${countryInfoPath}`);
  process.exit(1);
}

const countryInfo = fs.readFileSync(countryInfoPath, "utf-8");
const numToIso3: Record<string, string> = {};
const numericToIso3: Record<string, string> = {};

for (const line of countryInfo.split("\n")) {
  if (!line || line.startsWith("#")) continue;
  const parts = line.split("\t");
  if (parts.length > 2) {
    const iso3 = parts[1].trim();
    const numStr = parts[2].trim();
    if (iso3) {
      const num = numStr ? parseInt(numStr, 10) : 0;
      numericToIso3[String(num)] = iso3;
      const numPadded = numStr.padStart(3, "0");
      if (numPadded) {
        numToIso3[numPadded] = iso3;
      }
    }
  }
}

const worldAtlasPkg = require.resolve("world-atlas/countries-50m.json");
const topoData = JSON.parse(fs.readFileSync(worldAtlasPkg, "utf-8")) as Topology;
const geoCollection = topojson.feature(topoData, topoData.objects.countries);
const features = (
  "features" in geoCollection ? geoCollection.features : []
) as unknown as CountryFeature[];

const bboxes: Record<string, [number, number, number, number]> = {};

for (const feature of features) {
  if (!feature.id) {
    console.log(`Skipping feature without id: ${feature.properties?.name || "unknown"}`);
    continue;
  }
  const idStr = String(feature.id).padStart(3, "0");
  const iso3 = numToIso3[idStr];
  if (!iso3) {
    console.log(`Skipping unmapped id ${feature.id} (${feature.properties?.name || "unknown"})`);
    continue;
  }
  const bounds = d3.geoBounds(feature);
  bboxes[iso3] = [bounds[0][0], bounds[0][1], bounds[1][0], bounds[1][1]];
}

const sortedKeys = Object.keys(bboxes).sort();
const result: Record<string, [number, number, number, number] | string> = {
  $comment: "GENERATED by renderer/scripts/gen-country-bboxes.ts — DO NOT EDIT",
};

for (const key of sortedKeys) {
  result[key] = bboxes[key];
}

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, JSON.stringify(result, null, 2) + "\n", "utf-8");
console.log(`Wrote ${sortedKeys.length} country bboxes to ${outPath}`);

const sortedNumericKeys = Object.keys(numericToIso3).sort((a, b) => Number(a) - Number(b));
let countryCodesContent = "// GENERATED by renderer/scripts/gen-country-bboxes.ts — DO NOT EDIT\n\n";
countryCodesContent += "// Mapping from ISO 3166-1 numeric code to ISO3 country code\n";
countryCodesContent += "export const NUMERIC_TO_ISO3: Record<string, string> = {\n";
for (const key of sortedNumericKeys) {
  countryCodesContent += `  "${key}": "${numericToIso3[key]}",\n`;
}
countryCodesContent += "};\n";

fs.mkdirSync(path.dirname(countryCodesOutPath), { recursive: true });
fs.writeFileSync(countryCodesOutPath, countryCodesContent, "utf-8");
console.log(`Wrote ${sortedNumericKeys.length} country codes to ${countryCodesOutPath}`);
